name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.13"
              otp: "24.3.4.10"
          - pair:
              elixir: "1.17"
              otp: "27.0.1"
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@main
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}
          version-type: strict

      - uses: actions/cache@v4
        with:
          path: deps
          key: mix-deps-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get --check-locked

      - run: mix format --check-formatted

      - run: mix deps.unlock --check-unused

      - run: mix deps.compile

      - run: mix compile --no-optional-deps --warnings-as-errors

      - run: mix credo

      - run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
